# This file lists the minimal dependencies needed to build the documentation
# for sage-euler-product. Create a conda environment with these dependencies
# preinstalled with:
# conda env create -n sage-euler-product-docbuild -f ../environment.yml
# conda env update -n sage-euler-product-docbuild -f environment.yml
name: sage-euler-product-docbuild
channels:
  - conda-forge
dependencies:
  - sphinx
  - jupytext
  - myst-nb
  - furo
  - pip
  - pip:
   - pip
  - pip:
    - git+https://github.com/mikicard/sphinxcontrib-rsvgconverter.git
    - linkchecker
    - sphinx_rtd_theme
